apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: python-rds
  name: python-rds
spec:
  replicas: 2
  selector:
    matchLabels:
      run: python-rds
  template:
    metadata:
      labels:
        run: python-rds
    spec:
      containers:
      - image: ${IMAGE}
        name: python-rds
